name: main
on:
  push:
    branches:
      - main
    paths:
      - 'Directory.Build.props'

jobs:
  deploy-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack
        run: dotnet pack --no-build --configuration Release
      - name: Push NuGet package
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ vars.XUZEYU }}
